# Source from other scripts: source "$(dirname "$0")/mnt-paths.sh"
WORKBENCH_ROOT="${WORKBENCH_ROOT:-/workspaces/silentorb-workbench}"
MNT="${MNT:-${WORKBENCH_ROOT}/.mnt}"
TOME="${TOME:-${MNT}/tome}"
MARLOTH="${MARLOTH:-${MNT}/marloth-story}"
SILENTORB="${SILENTORB:-${MNT}/silentorb-web}"
TRANSLUCENCE="${TRANSLUCENCE:-${MNT}/translucence}"
IMP_TS="${IMP_TS:-${MNT}/imp-ts}"
IMP_RUST="${IMP_RUST:-${MNT}/imp-rust}"
IMP_SPEC="${IMP_SPEC:-${MNT}/imp-spec}"
